# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a83b0cf066dd7166a9db8bde36cef340995229cc064a67a7ec93143a3cc05d807a5b6ef235509ab55fe058c7dea03c1d89c5dbf9f578a1ef34bcb00fe5c5e1e4

test:
  secret_key_base: aeb23c511f9f6724742c2c7dd2e53a9d8664db1a021b38d27bb6ee318bd082d1f55eaa666bc665683949c89a6e7559cf272f71b0078190d932f8b7d4ecb8ad45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
